version: '3.6'

services:
  # Keycloak Server
  keycloak_web:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8180
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - 8180:8080
    depends_on:
      - keycloak_db

  # Banco de dados do Keycloak
  keycloak_db:
    image: postgres:16
    container_name: keycloak_db
    environment:
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
      POSTGRES_DB: keycloak
    ports:
      - 5433:5432
    volumes:
      - keycloak_data:/var/lib/postgresql/data

  # Banco de dados da aplicação
  app_db:
    image: postgres:16
    container_name: app_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: ecomaireview-service
    ports:
      - 5434:5432
    volumes:
      - app_data:/var/lib/postgresql/data

volumes:
  keycloak_data:
  app_data:
