server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param


spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ecomaireview-service
    username: app_user
    password: app_password
    driverClassName: org.postgresql.Driver
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}

  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

  flyway:
    url: jdbc:postgresql://localhost:5434/ecomaireview-service
    user: app_user
    password: app_password
    enabled: true
    baseline-on-migrate: true

  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: ${springkeycloak.auth.jwt.issuerUri}
            jwk-set-uri: ${springkeycloak.auth.jwt.issuerUri}/protocol/openid-connect/certs

origins: http://localhost:8080

springkeycloak:
  auth:
    jwt:
      issuerUri: http://localhost:8180/realms/EcomAIReview
      clientId: ecomaireview-api
      allowedAudiences:
        - "digitalagro-api"
#com:
#  c4-soft:
#    springaddons:
#      oidc:
#        ops:
#          # as this is an array of issuers, we may define more than one Keycloak realm
#          # or even completely different authorization servers (using other private claims for user roles)
#          - iss: ${issuer}
#            # for illustration purpose only: the default (iss) is probably a better option
#            username-claim: preferred_username
#            authorities:
#              - path: $.realm_access.roles
#                # for illustration purpose, the default is an empty string
#                prefix: ROLE_
#                # any valid JsonPath expression resolved to a list of strings is acceptable
#              - path: $.resource_access.*.roles
#        resourceserver:
#          # default access rule is "isAuthenticated" except for the path matched here (allowed to anonymous requests)
#          permit-all:
#            - "/actuator/health/readiness"
#            - "/actuator/health/liveness"
#            - "/v3/api-docs/**"
#            - "/v3/api-docs"
#            - "/swagger-ui/**"
#        cors:
#          - path: /**
#            allowed-origin-patterns: ${origins}

#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 100MB
#
#  mvc:
#    pathmatch:
#      matching-strategy: ant-path-matcher
#
#  jackson:
#    serialization:
#      write-dates-as-timestamps: false
#    deserialization:
#      accept-single-value-as-array: true
#    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
#    time-zone: America/Sao_Paulo
#
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${springkeycloak.auth.jwt.issuerUri}
#          jwk-set-uri: ${springkeycloak.auth.jwt.issuerUri}/protocol/openid-connect/certs
#
#
#server:
#  port: 8085
#
#gcp:
#  bucketName: ds-developer
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  endpoint:
#    health:
#      show-details: always
#logging:
#  level:
#    root: debug

